//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agri_Market
{
    public partial class AboutProduct
    {
        protected global::System.Web.UI.WebControls.Panel pnlProductUnavailable;
        protected global::System.Web.UI.WebControls.Panel pnlProduct;
        protected global::System.Web.UI.WebControls.Image imgProduct;
        protected global::System.Web.UI.WebControls.Label lblCategory;
        protected global::System.Web.UI.WebControls.Label lblProductName;
        protected global::System.Web.UI.WebControls.Label lblPrice;
        protected global::System.Web.UI.WebControls.Label lblUnitOfMeasure;
        protected global::System.Web.UI.WebControls.Label lblDescription;
        protected global::System.Web.UI.WebControls.Label lblStockQuantity;
    }
}
