//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Agri_Market
{
    public partial class registerPage
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.RadioButtonList roleSelection;

        protected global::System.Web.UI.WebControls.TextBox myemail;

        protected global::System.Web.UI.WebControls.TextBox myname;

        protected global::System.Web.UI.WebControls.TextBox mysurname;

        protected global::System.Web.UI.WebControls.TextBox myphonenum;

        protected global::System.Web.UI.WebControls.TextBox mypassword;

        protected global::System.Web.UI.WebControls.Panel farmerDetailsPanel;

        protected global::System.Web.UI.WebControls.TextBox farmName;

        protected global::System.Web.UI.WebControls.TextBox farmLocation;

        protected global::System.Web.UI.WebControls.TextBox farmDescription;

        protected global::System.Web.UI.WebControls.Panel adminCodePanel;

        protected global::System.Web.UI.WebControls.TextBox adminCode;

        protected global::System.Web.UI.WebControls.Button mybutton;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}